SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_DRIVS_UnReg]
  @Codigo INT
AS
BEGIN
  SELECT VEHI.Item, VEHI.Codigo, VEHi.TYPE_cTABBRND, VEHI.TYPE_cCODBRND, VEHI.TYPE_cTABVSTA, VEHI.TYPE_cCODVSTA
    , VEHI.VEHI_UnitType, VEHI.VEHI_VehiclePlate, VEHI.DRIV_dBirthDate, VEHI.DRIV_cAddress
    FROM SAIR_DRIVER VEHI
  WHERE VEHI.Codigo = @Codigo;
END


GO
