
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_LISTOPERATIONS]
AS
BEGIN
	SELECT OPERAT.OPER_Id AS OperationId, OPERAT.OPER_Name AS OperationName, OPERAT.OPER_DBName AS DataBaseName, OPERAT.OPER_DBId AS DataBaseId
	, USERS.UserName AS UserName
	FROM dbo.SAIR_OPERATIONS OPERAT
	LEFT JOIN dbo.AspNetUsers USERS
	ON OPERAT.OPER_Id = USERS.OperationId
END
GO
