
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_OPERS]
WITH EXECUTE AS CALLER
AS
BEGIN
	SELECT OPER.OPER_Id, OPER.OPER_cApellidoPaterno, OPER.OPER_cApellidoMaterno, OPER.OPER_cNombre, OPER.OPER_cCorreo
	, OPER.VEHI_Id,VEHI.VEHI_VehiclePlate + ' / ' + BRNDTY.TYPE_cDescription AS VEHI_cDescripcion ,OPER.PUES_Id
	FROM SAIR_OPERARIOS OPER
	LEFT JOIN SAIR_VEHICLE VEHI
		ON OPER.VEHI_Id=VEHI.Codigo
	LEFT JOIN dbo.SAIR_TYPES BRNDTY
	ON BRNDTY.TYPE_cCodTable = VEHI.TYPE_cTABBRND AND BRNDTY.TYPE_cCodType = VEHI.TYPE_cCODBRND;
END
GO
