SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_VEALU]
	@VEAL_Id int,
	@VEAL_TokenSMS nvarchar(80)
AS
BEGIN
	UPDATE dbo.SAIR_VehicleAlerts
	SET VEAL_AlertSended = 1,
	VEAL_TokenSMS = @VEAL_TokenSMS
	WHERE VEAL_Id = @VEAL_Id;

END
GO
