SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_OPERU]
	@OPER_Id INT,
	@OPER_Name NVARCHAR(80)
AS
BEGIN
	UPDATE dbo.SAIR_OPERATIONS
	SET OPER_Name = @OPER_Name
	WHERE OPER_Id = @OPER_Id;
END
GO
