SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SAIR_OPERS]
WITH EXECUTE AS CALLER
AS
BEGIN
	select OPER.OPER_Id, OPER.OPER_cApellidoPaterno, OPER.OPER_cApellidoMaterno, 
	OPER.OPER_cNombre, OPER.OPER_cCorreo, OPER.VEHI_Id,VEHI.PlacaTracto AS VEHI_cDescripcion,OPER.PUES_Id
	from SAIR_OPERARIOS OPER LEFT JOIN SAIR_VEHICLE VEHI ON OPER.VEHI_Id=VEHI.Codigo;
END
GO
