// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SERVOSA.SAIR.WEB.Controllers
{
    public partial class DriverDataController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DriverDataController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Data()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Data);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CabeceraVehiculo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CabeceraVehiculo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DatosVariableVehiculo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DatosVariableVehiculo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetFileModalManager()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFileModalManager);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteFile()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadVariable()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadVariable);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult DownloadDriverData()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadDriverData);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DriverDataController Actions { get { return MVC.DriverData; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "DriverData";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "DriverData";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Data = "Data";
            public readonly string CabeceraVehiculo = "CabeceraVehiculo";
            public readonly string DatosVariableVehiculo = "DatosVariableVehiculo";
            public readonly string GetFileModalManager = "GetFileModalManager";
            public readonly string ListFilesByTableAndDriver = "ListFilesByTableAndDriver";
            public readonly string DeleteFile = "DeleteFile";
            public readonly string DownloadVariable = "DownloadVariable";
            public readonly string DownloadDriverData = "DownloadDriverData";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Data = "Data";
            public const string CabeceraVehiculo = "CabeceraVehiculo";
            public const string DatosVariableVehiculo = "DatosVariableVehiculo";
            public const string GetFileModalManager = "GetFileModalManager";
            public const string ListFilesByTableAndDriver = "ListFilesByTableAndDriver";
            public const string DeleteFile = "DeleteFile";
            public const string DownloadVariable = "DownloadVariable";
            public const string DownloadDriverData = "DownloadDriverData";
        }


        static readonly ActionParamsClass_Data s_params_Data = new ActionParamsClass_Data();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Data DataParams { get { return s_params_Data; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Data
        {
            public readonly string driverCode = "driverCode";
        }
        static readonly ActionParamsClass_CabeceraVehiculo s_params_CabeceraVehiculo = new ActionParamsClass_CabeceraVehiculo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CabeceraVehiculo CabeceraVehiculoParams { get { return s_params_CabeceraVehiculo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CabeceraVehiculo
        {
            public readonly string driverCode = "driverCode";
        }
        static readonly ActionParamsClass_DatosVariableVehiculo s_params_DatosVariableVehiculo = new ActionParamsClass_DatosVariableVehiculo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DatosVariableVehiculo DatosVariableVehiculoParams { get { return s_params_DatosVariableVehiculo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DatosVariableVehiculo
        {
            public readonly string driverCode = "driverCode";
            public readonly string variableName = "variableName";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetFileModalManager s_params_GetFileModalManager = new ActionParamsClass_GetFileModalManager();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFileModalManager GetFileModalManagerParams { get { return s_params_GetFileModalManager; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFileModalManager
        {
            public readonly string tableName = "tableName";
            public readonly string driverCode = "driverCode";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ListFilesByTableAndDriver s_params_ListFilesByTableAndDriver = new ActionParamsClass_ListFilesByTableAndDriver();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListFilesByTableAndDriver ListFilesByTableAndDriverParams { get { return s_params_ListFilesByTableAndDriver; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListFilesByTableAndDriver
        {
            public readonly string jtStartIndex = "jtStartIndex";
            public readonly string jtPageSize = "jtPageSize";
            public readonly string jtSorting = "jtSorting";
            public readonly string tableName = "tableName";
            public readonly string driverCode = "driverCode";
        }
        static readonly ActionParamsClass_DeleteFile s_params_DeleteFile = new ActionParamsClass_DeleteFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteFile DeleteFileParams { get { return s_params_DeleteFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteFile
        {
            public readonly string ComposedPrimaryKey = "ComposedPrimaryKey";
        }
        static readonly ActionParamsClass_DownloadVariable s_params_DownloadVariable = new ActionParamsClass_DownloadVariable();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadVariable DownloadVariableParams { get { return s_params_DownloadVariable; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadVariable
        {
            public readonly string tableName = "tableName";
        }
        static readonly ActionParamsClass_DownloadDriverData s_params_DownloadDriverData = new ActionParamsClass_DownloadDriverData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadDriverData DownloadDriverDataParams { get { return s_params_DownloadDriverData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadDriverData
        {
            public readonly string driverId = "driverId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Data = "Data";
            }
            public readonly string Data = "~/Views/DriverData/Data.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DriverDataController : SERVOSA.SAIR.WEB.Controllers.DriverDataController
    {
        public T4MVC_DriverDataController() : base(Dummy.Instance) { }

        [NonAction]
        partial void DataOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int driverCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult Data(int driverCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverCode", driverCode);
            DataOverride(callInfo, driverCode);
            return callInfo;
        }

        [NonAction]
        partial void CabeceraVehiculoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int driverCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult CabeceraVehiculo(int driverCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CabeceraVehiculo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverCode", driverCode);
            CabeceraVehiculoOverride(callInfo, driverCode);
            return callInfo;
        }

        [NonAction]
        partial void DatosVariableVehiculoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int driverCode, string variableName);

        [NonAction]
        public override System.Web.Mvc.ActionResult DatosVariableVehiculo(int driverCode, string variableName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DatosVariableVehiculo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverCode", driverCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "variableName", variableName);
            DatosVariableVehiculoOverride(callInfo, driverCode, variableName);
            return callInfo;
        }

        [NonAction]
        partial void DatosVariableVehiculoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SERVOSA.SAIR.SERVICE.Models.DriverVariableDataServiceModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult DatosVariableVehiculo(SERVOSA.SAIR.SERVICE.Models.DriverVariableDataServiceModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DatosVariableVehiculo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DatosVariableVehiculoOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetFileModalManagerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string tableName, int driverCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFileModalManager(string tableName, int driverCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFileModalManager);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tableName", tableName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverCode", driverCode);
            GetFileModalManagerOverride(callInfo, tableName, driverCode);
            return callInfo;
        }

        [NonAction]
        partial void GetFileModalManagerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, SERVOSA.SAIR.SERVICE.Models.TableData.DriverFiles model);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFileModalManager(SERVOSA.SAIR.SERVICE.Models.TableData.DriverFiles model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFileModalManager);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetFileModalManagerOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ListFilesByTableAndDriverOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int jtStartIndex, int jtPageSize, string jtSorting, string tableName, int? driverCode);

        [NonAction]
        public override System.Web.Mvc.JsonResult ListFilesByTableAndDriver(int jtStartIndex, int jtPageSize, string jtSorting, string tableName, int? driverCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListFilesByTableAndDriver);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtStartIndex", jtStartIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtPageSize", jtPageSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "jtSorting", jtSorting);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tableName", tableName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverCode", driverCode);
            ListFilesByTableAndDriverOverride(callInfo, jtStartIndex, jtPageSize, jtSorting, tableName, driverCode);
            return callInfo;
        }

        [NonAction]
        partial void DeleteFileOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string ComposedPrimaryKey);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteFile(string ComposedPrimaryKey)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ComposedPrimaryKey", ComposedPrimaryKey);
            DeleteFileOverride(callInfo, ComposedPrimaryKey);
            return callInfo;
        }

        [NonAction]
        partial void DownloadVariableOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string tableName);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadVariable(string tableName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadVariable);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tableName", tableName);
            DownloadVariableOverride(callInfo, tableName);
            return callInfo;
        }

        [NonAction]
        partial void DownloadDriverDataOverride(T4MVC_System_Web_Mvc_FileResult callInfo, int driverId);

        [NonAction]
        public override System.Web.Mvc.FileResult DownloadDriverData(int driverId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.DownloadDriverData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "driverId", driverId);
            DownloadDriverDataOverride(callInfo, driverId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
