// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static SERVOSA.SAIR.WEB.Controllers.AccountController Account = new SERVOSA.SAIR.WEB.Controllers.T4MVC_AccountController();
    public static SERVOSA.SAIR.WEB.Controllers.DriverController Driver = new SERVOSA.SAIR.WEB.Controllers.T4MVC_DriverController();
    public static SERVOSA.SAIR.WEB.Controllers.DriverDashboardController DriverDashboard = new SERVOSA.SAIR.WEB.Controllers.T4MVC_DriverDashboardController();
    public static SERVOSA.SAIR.WEB.Controllers.DriverDataController DriverData = new SERVOSA.SAIR.WEB.Controllers.T4MVC_DriverDataController();
    public static SERVOSA.SAIR.WEB.Controllers.DriverVariableTasksController DriverVariableTasks = new SERVOSA.SAIR.WEB.Controllers.T4MVC_DriverVariableTasksController();
    public static SERVOSA.SAIR.WEB.Controllers.HomeController Home = new SERVOSA.SAIR.WEB.Controllers.T4MVC_HomeController();
    public static SERVOSA.SAIR.WEB.Controllers.LoadFileController LoadFile = new SERVOSA.SAIR.WEB.Controllers.T4MVC_LoadFileController();
    public static SERVOSA.SAIR.WEB.Controllers.ManageController Manage = new SERVOSA.SAIR.WEB.Controllers.T4MVC_ManageController();
    public static SERVOSA.SAIR.WEB.Controllers.OldDriverController OldDriver = new SERVOSA.SAIR.WEB.Controllers.T4MVC_OldDriverController();
    public static SERVOSA.SAIR.WEB.Controllers.OldDriverDataController OldDriverData = new SERVOSA.SAIR.WEB.Controllers.T4MVC_OldDriverDataController();
    public static SERVOSA.SAIR.WEB.Controllers.OperationsController Operations = new SERVOSA.SAIR.WEB.Controllers.T4MVC_OperationsController();
    public static SERVOSA.SAIR.WEB.Controllers.VariableTasksController VariableTasks = new SERVOSA.SAIR.WEB.Controllers.T4MVC_VariableTasksController();
    public static SERVOSA.SAIR.WEB.Controllers.VehicleController Vehicle = new SERVOSA.SAIR.WEB.Controllers.T4MVC_VehicleController();
    public static SERVOSA.SAIR.WEB.Controllers.VehicleDataController VehicleData = new SERVOSA.SAIR.WEB.Controllers.T4MVC_VehicleDataController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileResult : System.Web.Mvc.FileResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override void WriteFile(System.Web.HttpResponseBase response) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string handlebars_latest_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/handlebars-latest.min.js") ? Url("handlebars-latest.min.js") : Url("handlebars-latest.js");
        public static readonly string handlebars_min_latest_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/handlebars.min-latest.min.js") ? Url("handlebars.min-latest.min.js") : Url("handlebars.min-latest.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_ui_1_9_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.9.2.min.js") ? Url("jquery-ui-1.9.2.min.js") : Url("jquery-ui-1.9.2.js");
        public static readonly string jquery_ui_1_9_2_min_js = Url("jquery-ui-1.9.2.min.js");
        public static readonly string jquery_ui_datepicker_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker-es.min.js") ? Url("jquery.ui.datepicker-es.min.js") : Url("jquery.ui.datepicker-es.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string jquery_validationEngine_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validationEngine-es.min.js") ? Url("jquery.validationEngine-es.min.js") : Url("jquery.validationEngine-es.js");
        public static readonly string jquery_validationEngine_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validationEngine.min.js") ? Url("jquery.validationEngine.min.js") : Url("jquery.validationEngine.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jtable {
            private const string URLPATH = "~/Scripts/jtable";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class extensions {
                private const string URLPATH = "~/Scripts/jtable/extensions";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string jquery_jtable_aspnetpagemethods_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.aspnetpagemethods.min.js") ? Url("jquery.jtable.aspnetpagemethods.min.js") : Url("jquery.jtable.aspnetpagemethods.js");
                public static readonly string jquery_jtable_aspnetpagemethods_min_js = Url("jquery.jtable.aspnetpagemethods.min.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class external {
                private const string URLPATH = "~/Scripts/jtable/external";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string json2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/json2.min.js") ? Url("json2.min.js") : Url("json2.js");
                public static readonly string json2_min_js = Url("json2.min.js");
            }
        
            public static readonly string jquery_jtable_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.min.js") ? Url("jquery.jtable.min.js") : Url("jquery.jtable.js");
            public static readonly string jquery_jtable_min_js = Url("jquery.jtable.min.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class localization {
                private const string URLPATH = "~/Scripts/jtable/localization";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string jquery_jtable_bd_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.bd.min.js") ? Url("jquery.jtable.bd.min.js") : Url("jquery.jtable.bd.js");
                public static readonly string jquery_jtable_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.ca.min.js") ? Url("jquery.jtable.ca.min.js") : Url("jquery.jtable.ca.js");
                public static readonly string jquery_jtable_cz_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.cz.min.js") ? Url("jquery.jtable.cz.min.js") : Url("jquery.jtable.cz.js");
                public static readonly string jquery_jtable_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.de.min.js") ? Url("jquery.jtable.de.min.js") : Url("jquery.jtable.de.js");
                public static readonly string jquery_jtable_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.es.min.js") ? Url("jquery.jtable.es.min.js") : Url("jquery.jtable.es.js");
                public static readonly string jquery_jtable_fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.fa.min.js") ? Url("jquery.jtable.fa.min.js") : Url("jquery.jtable.fa.js");
                public static readonly string jquery_jtable_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.fr.min.js") ? Url("jquery.jtable.fr.min.js") : Url("jquery.jtable.fr.js");
                public static readonly string jquery_jtable_hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.hr.min.js") ? Url("jquery.jtable.hr.min.js") : Url("jquery.jtable.hr.js");
                public static readonly string jquery_jtable_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.hu.min.js") ? Url("jquery.jtable.hu.min.js") : Url("jquery.jtable.hu.js");
                public static readonly string jquery_jtable_id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.id.min.js") ? Url("jquery.jtable.id.min.js") : Url("jquery.jtable.id.js");
                public static readonly string jquery_jtable_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.it.min.js") ? Url("jquery.jtable.it.min.js") : Url("jquery.jtable.it.js");
                public static readonly string jquery_jtable_lt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.lt.min.js") ? Url("jquery.jtable.lt.min.js") : Url("jquery.jtable.lt.js");
                public static readonly string jquery_jtable_nl_NL_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.nl-NL.min.js") ? Url("jquery.jtable.nl-NL.min.js") : Url("jquery.jtable.nl-NL.js");
                public static readonly string jquery_jtable_no_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.no.min.js") ? Url("jquery.jtable.no.min.js") : Url("jquery.jtable.no.js");
                public static readonly string jquery_jtable_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.pl.min.js") ? Url("jquery.jtable.pl.min.js") : Url("jquery.jtable.pl.js");
                public static readonly string jquery_jtable_pt_BR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.pt-BR.min.js") ? Url("jquery.jtable.pt-BR.min.js") : Url("jquery.jtable.pt-BR.js");
                public static readonly string jquery_jtable_pt_PT_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.pt-PT.min.js") ? Url("jquery.jtable.pt-PT.min.js") : Url("jquery.jtable.pt-PT.js");
                public static readonly string jquery_jtable_ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.ro.min.js") ? Url("jquery.jtable.ro.min.js") : Url("jquery.jtable.ro.js");
                public static readonly string jquery_jtable_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.ru.min.js") ? Url("jquery.jtable.ru.min.js") : Url("jquery.jtable.ru.js");
                public static readonly string jquery_jtable_se_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.se.min.js") ? Url("jquery.jtable.se.min.js") : Url("jquery.jtable.se.js");
                public static readonly string jquery_jtable_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.tr.min.js") ? Url("jquery.jtable.tr.min.js") : Url("jquery.jtable.tr.js");
                public static readonly string jquery_jtable_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.vi.min.js") ? Url("jquery.jtable.vi.min.js") : Url("jquery.jtable.vi.js");
                public static readonly string jquery_jtable_zh_CN_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jtable.zh-CN.min.js") ? Url("jquery.jtable.zh-CN.min.js") : Url("jquery.jtable.zh-CN.js");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class themes {
                private const string URLPATH = "~/Scripts/jtable/themes";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class basic {
                    private const string URLPATH = "~/Scripts/jtable/themes/basic";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string close_png = Url("close.png");
                    public static readonly string column_asc_png = Url("column-asc.png");
                    public static readonly string column_desc_png = Url("column-desc.png");
                    public static readonly string column_sortable_png = Url("column-sortable.png");
                    public static readonly string delete_png = Url("delete.png");
                    public static readonly string edit_png = Url("edit.png");
                    public static readonly string jtable_basic_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable_basic.min.css") ? Url("jtable_basic.min.css") : Url("jtable_basic.css");
                    public static readonly string jtable_basic_less = Url("jtable_basic.less");
                    public static readonly string jtable_basic_min_css = Url("jtable_basic.min.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class jqueryui {
                    private const string URLPATH = "~/Scripts/jtable/themes/jqueryui";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string add_png = Url("add.png");
                    public static readonly string bg_thead_png = Url("bg-thead.png");
                    public static readonly string close_png = Url("close.png");
                    public static readonly string column_asc_png = Url("column-asc.png");
                    public static readonly string column_desc_png = Url("column-desc.png");
                    public static readonly string column_sortable_png = Url("column-sortable.png");
                    public static readonly string delete_png = Url("delete.png");
                    public static readonly string edit_png = Url("edit.png");
                    public static readonly string jtable_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable_jqueryui.min.css") ? Url("jtable_jqueryui.min.css") : Url("jtable_jqueryui.css");
                    public static readonly string jtable_jqueryui_less = Url("jtable_jqueryui.less");
                    public static readonly string jtable_jqueryui_min_css = Url("jtable_jqueryui.min.css");
                    public static readonly string loading_gif = Url("loading.gif");
                }
            
                public static readonly string jtable_theme_base_less = Url("jtable_theme_base.less");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class lightcolor {
                    private const string URLPATH = "~/Scripts/jtable/themes/lightcolor";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string add_png = Url("add.png");
                    public static readonly string bg_thead_png = Url("bg-thead.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class blue {
                        private const string URLPATH = "~/Scripts/jtable/themes/lightcolor/blue";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    public static readonly string close_png = Url("close.png");
                    public static readonly string column_asc_png = Url("column-asc.png");
                    public static readonly string column_desc_png = Url("column-desc.png");
                    public static readonly string column_sortable_png = Url("column-sortable.png");
                    public static readonly string delete_png = Url("delete.png");
                    public static readonly string edit_png = Url("edit.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class gray {
                        private const string URLPATH = "~/Scripts/jtable/themes/lightcolor/gray";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class green {
                        private const string URLPATH = "~/Scripts/jtable/themes/lightcolor/green";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    public static readonly string jtable_lightcolor_base_less = Url("jtable_lightcolor_base.less");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class orange {
                        private const string URLPATH = "~/Scripts/jtable/themes/lightcolor/orange";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class red {
                        private const string URLPATH = "~/Scripts/jtable/themes/lightcolor/red";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class metro {
                    private const string URLPATH = "~/Scripts/jtable/themes/metro";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string add_png = Url("add.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class blue {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/blue";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class brown {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/brown";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    public static readonly string close_png = Url("close.png");
                    public static readonly string column_asc_png = Url("column-asc.png");
                    public static readonly string column_desc_png = Url("column-desc.png");
                    public static readonly string column_sortable_png = Url("column-sortable.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class crimson {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/crimson";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class darkgray {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/darkgray";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class darkorange {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/darkorange";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    public static readonly string delete_png = Url("delete.png");
                    public static readonly string edit_png = Url("edit.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class green {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/green";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    public static readonly string jtable_metro_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable_metro_base.min.css") ? Url("jtable_metro_base.min.css") : Url("jtable_metro_base.css");
                    public static readonly string jtable_metro_base_less = Url("jtable_metro_base.less");
                    public static readonly string jtable_metro_base_min_css = Url("jtable_metro_base.min.css");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class lightgray {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/lightgray";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class pink {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/pink";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class purple {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/purple";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class red {
                        private const string URLPATH = "~/Scripts/jtable/themes/metro/red";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jtable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jtable.min.css") ? Url("jtable.min.css") : Url("jtable.css");
                        public static readonly string jtable_less = Url("jtable.less");
                        public static readonly string jtable_min_css = Url("jtable.min.css");
                        public static readonly string loading_gif = Url("loading.gif");
                    }
                
                }
            
            }
        
        }
    
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class ViewController {
            private const string URLPATH = "~/Scripts/ViewController";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Driver {
                private const string URLPATH = "~/Scripts/ViewController/Driver";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string DriverDataViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverDataViewController.min.js") ? Url("DriverDataViewController.min.js") : Url("DriverDataViewController.js");
                public static readonly string DriverUploadViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverUploadViewController.min.js") ? Url("DriverUploadViewController.min.js") : Url("DriverUploadViewController.js");
                public static readonly string DriverViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverViewController.min.js") ? Url("DriverViewController.min.js") : Url("DriverViewController.js");
                public static readonly string OldDriverDataViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OldDriverDataViewController.min.js") ? Url("OldDriverDataViewController.min.js") : Url("OldDriverDataViewController.js");
                public static readonly string OldDriverUploadViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OldDriverUploadViewController.min.js") ? Url("OldDriverUploadViewController.min.js") : Url("OldDriverUploadViewController.js");
                public static readonly string OldDriverViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OldDriverViewController.min.js") ? Url("OldDriverViewController.min.js") : Url("OldDriverViewController.js");
            }
        
            public static readonly string DriverDataViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverDataViewController.min.js") ? Url("DriverDataViewController.min.js") : Url("DriverDataViewController.js");
            public static readonly string DriverSERVOSA_Core_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverSERVOSA.Core.min.js") ? Url("DriverSERVOSA.Core.min.js") : Url("DriverSERVOSA.Core.js");
            public static readonly string DriverSERVOSAViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverSERVOSAViewController.min.js") ? Url("DriverSERVOSAViewController.min.js") : Url("DriverSERVOSAViewController.js");
            public static readonly string DriverUploadViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverUploadViewController.min.js") ? Url("DriverUploadViewController.min.js") : Url("DriverUploadViewController.js");
            public static readonly string DriverViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DriverViewController.min.js") ? Url("DriverViewController.min.js") : Url("DriverViewController.js");
            public static readonly string OldDriverViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OldDriverViewController.min.js") ? Url("OldDriverViewController.min.js") : Url("OldDriverViewController.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Operations {
                private const string URLPATH = "~/Scripts/ViewController/Operations";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string OperationViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OperationViewController.min.js") ? Url("OperationViewController.min.js") : Url("OperationViewController.js");
            }
        
            public static readonly string SERVOSA_Core_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/SERVOSA.Core.min.js") ? Url("SERVOSA.Core.min.js") : Url("SERVOSA.Core.js");
            public static readonly string SERVOSAViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/SERVOSAViewController.min.js") ? Url("SERVOSAViewController.min.js") : Url("SERVOSAViewController.js");
            public static readonly string VehicleDataViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/VehicleDataViewController.min.js") ? Url("VehicleDataViewController.min.js") : Url("VehicleDataViewController.js");
            public static readonly string VehicleUploadViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/VehicleUploadViewController.min.js") ? Url("VehicleUploadViewController.min.js") : Url("VehicleUploadViewController.js");
            public static readonly string VehicleViewController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/VehicleViewController.min.js") ? Url("VehicleViewController.min.js") : Url("VehicleViewController.js");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                public static readonly string jquery_ui_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.menu.min.css") ? Url("jquery.ui.menu.min.css") : Url("jquery.ui.menu.css");
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                public static readonly string jquery_ui_spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.spinner.min.css") ? Url("jquery.ui.spinner.min.css") : Url("jquery.ui.spinner.css");
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                public static readonly string jquery_ui_tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tooltip.min.css") ? Url("jquery.ui.tooltip.min.css") : Url("jquery.ui.tooltip.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    private const string URLPATH = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_menu_min_css = Url("jquery.ui.menu.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_spinner_min_css = Url("jquery.ui.spinner.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                    public static readonly string jquery_ui_tooltip_min_css = Url("jquery.ui.tooltip.min.css");
                }
            
            }
        
        }
    
        public static readonly string validationEngine_jquery_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/validationEngine.jquery.min.css") ? Url("validationEngine.jquery.min.css") : Url("validationEngine.jquery.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class jtable 
            {
                public static partial class extensions 
                {
                    public static class Assets
                    {
                        public const string jquery_jtable_aspnetpagemethods_js = "~/Scripts/jtable/extensions/jquery.jtable.aspnetpagemethods.js"; 
                        public const string jquery_jtable_aspnetpagemethods_min_js = "~/Scripts/jtable/extensions/jquery.jtable.aspnetpagemethods.min.js"; 
                    }
                }
                public static partial class external 
                {
                    public static class Assets
                    {
                        public const string json2_js = "~/Scripts/jtable/external/json2.js"; 
                        public const string json2_min_js = "~/Scripts/jtable/external/json2.min.js"; 
                    }
                }
                public static partial class localization 
                {
                    public static class Assets
                    {
                        public const string jquery_jtable_bd_js = "~/Scripts/jtable/localization/jquery.jtable.bd.js"; 
                        public const string jquery_jtable_ca_js = "~/Scripts/jtable/localization/jquery.jtable.ca.js"; 
                        public const string jquery_jtable_cz_js = "~/Scripts/jtable/localization/jquery.jtable.cz.js"; 
                        public const string jquery_jtable_de_js = "~/Scripts/jtable/localization/jquery.jtable.de.js"; 
                        public const string jquery_jtable_es_js = "~/Scripts/jtable/localization/jquery.jtable.es.js"; 
                        public const string jquery_jtable_fa_js = "~/Scripts/jtable/localization/jquery.jtable.fa.js"; 
                        public const string jquery_jtable_fr_js = "~/Scripts/jtable/localization/jquery.jtable.fr.js"; 
                        public const string jquery_jtable_hr_js = "~/Scripts/jtable/localization/jquery.jtable.hr.js"; 
                        public const string jquery_jtable_hu_js = "~/Scripts/jtable/localization/jquery.jtable.hu.js"; 
                        public const string jquery_jtable_id_js = "~/Scripts/jtable/localization/jquery.jtable.id.js"; 
                        public const string jquery_jtable_it_js = "~/Scripts/jtable/localization/jquery.jtable.it.js"; 
                        public const string jquery_jtable_lt_js = "~/Scripts/jtable/localization/jquery.jtable.lt.js"; 
                        public const string jquery_jtable_nl_NL_js = "~/Scripts/jtable/localization/jquery.jtable.nl-NL.js"; 
                        public const string jquery_jtable_no_js = "~/Scripts/jtable/localization/jquery.jtable.no.js"; 
                        public const string jquery_jtable_pl_js = "~/Scripts/jtable/localization/jquery.jtable.pl.js"; 
                        public const string jquery_jtable_pt_BR_js = "~/Scripts/jtable/localization/jquery.jtable.pt-BR.js"; 
                        public const string jquery_jtable_pt_PT_js = "~/Scripts/jtable/localization/jquery.jtable.pt-PT.js"; 
                        public const string jquery_jtable_ro_js = "~/Scripts/jtable/localization/jquery.jtable.ro.js"; 
                        public const string jquery_jtable_ru_js = "~/Scripts/jtable/localization/jquery.jtable.ru.js"; 
                        public const string jquery_jtable_se_js = "~/Scripts/jtable/localization/jquery.jtable.se.js"; 
                        public const string jquery_jtable_tr_js = "~/Scripts/jtable/localization/jquery.jtable.tr.js"; 
                        public const string jquery_jtable_vi_js = "~/Scripts/jtable/localization/jquery.jtable.vi.js"; 
                        public const string jquery_jtable_zh_CN_js = "~/Scripts/jtable/localization/jquery.jtable.zh-CN.js"; 
                    }
                }
                public static partial class themes 
                {
                    public static partial class basic 
                    {
                        public static class Assets
                        {
                            public const string jtable_basic_css = "~/Scripts/jtable/themes/basic/jtable_basic.css";
                            public const string jtable_basic_min_css = "~/Scripts/jtable/themes/basic/jtable_basic.min.css";
                        }
                    }
                    public static partial class jqueryui 
                    {
                        public static class Assets
                        {
                            public const string jtable_jqueryui_css = "~/Scripts/jtable/themes/jqueryui/jtable_jqueryui.css";
                            public const string jtable_jqueryui_min_css = "~/Scripts/jtable/themes/jqueryui/jtable_jqueryui.min.css";
                        }
                    }
                    public static partial class lightcolor 
                    {
                        public static partial class blue 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/lightcolor/blue/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/lightcolor/blue/jtable.min.css";
                            }
                        }
                        public static partial class gray 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/lightcolor/gray/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/lightcolor/gray/jtable.min.css";
                            }
                        }
                        public static partial class green 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/lightcolor/green/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/lightcolor/green/jtable.min.css";
                            }
                        }
                        public static partial class orange 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/lightcolor/orange/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/lightcolor/orange/jtable.min.css";
                            }
                        }
                        public static partial class red 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/lightcolor/red/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/lightcolor/red/jtable.min.css";
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static partial class metro 
                    {
                        public static partial class blue 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/blue/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/blue/jtable.min.css";
                            }
                        }
                        public static partial class brown 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/brown/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/brown/jtable.min.css";
                            }
                        }
                        public static partial class crimson 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/crimson/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/crimson/jtable.min.css";
                            }
                        }
                        public static partial class darkgray 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/darkgray/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/darkgray/jtable.min.css";
                            }
                        }
                        public static partial class darkorange 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/darkorange/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/darkorange/jtable.min.css";
                            }
                        }
                        public static partial class green 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/green/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/green/jtable.min.css";
                            }
                        }
                        public static partial class lightgray 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/lightgray/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/lightgray/jtable.min.css";
                            }
                        }
                        public static partial class pink 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/pink/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/pink/jtable.min.css";
                            }
                        }
                        public static partial class purple 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/purple/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/purple/jtable.min.css";
                            }
                        }
                        public static partial class red 
                        {
                            public static class Assets
                            {
                                public const string jtable_css = "~/Scripts/jtable/themes/metro/red/jtable.css";
                                public const string jtable_min_css = "~/Scripts/jtable/themes/metro/red/jtable.min.css";
                            }
                        }
                        public static class Assets
                        {
                            public const string jtable_metro_base_css = "~/Scripts/jtable/themes/metro/jtable_metro_base.css";
                            public const string jtable_metro_base_min_css = "~/Scripts/jtable/themes/metro/jtable_metro_base.min.css";
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                    public const string jquery_jtable_js = "~/Scripts/jtable/jquery.jtable.js"; 
                    public const string jquery_jtable_min_js = "~/Scripts/jtable/jquery.jtable.min.js"; 
                }
            }
            public static partial class ViewController 
            {
                public static partial class Driver 
                {
                    public static class Assets
                    {
                        public const string DriverDataViewController_js = "~/Scripts/ViewController/Driver/DriverDataViewController.js"; 
                        public const string DriverUploadViewController_js = "~/Scripts/ViewController/Driver/DriverUploadViewController.js"; 
                        public const string DriverViewController_js = "~/Scripts/ViewController/Driver/DriverViewController.js"; 
                        public const string OldDriverDataViewController_js = "~/Scripts/ViewController/Driver/OldDriverDataViewController.js"; 
                        public const string OldDriverUploadViewController_js = "~/Scripts/ViewController/Driver/OldDriverUploadViewController.js"; 
                        public const string OldDriverViewController_js = "~/Scripts/ViewController/Driver/OldDriverViewController.js"; 
                    }
                }
                public static partial class Operations 
                {
                    public static class Assets
                    {
                        public const string OperationViewController_js = "~/Scripts/ViewController/Operations/OperationViewController.js"; 
                    }
                }
                public static class Assets
                {
                    public const string DriverDataViewController_js = "~/Scripts/ViewController/DriverDataViewController.js"; 
                    public const string DriverSERVOSA_Core_js = "~/Scripts/ViewController/DriverSERVOSA.Core.js"; 
                    public const string DriverSERVOSAViewController_js = "~/Scripts/ViewController/DriverSERVOSAViewController.js"; 
                    public const string DriverUploadViewController_js = "~/Scripts/ViewController/DriverUploadViewController.js"; 
                    public const string DriverViewController_js = "~/Scripts/ViewController/DriverViewController.js"; 
                    public const string OldDriverViewController_js = "~/Scripts/ViewController/OldDriverViewController.js"; 
                    public const string SERVOSA_Core_js = "~/Scripts/ViewController/SERVOSA.Core.js"; 
                    public const string SERVOSAViewController_js = "~/Scripts/ViewController/SERVOSAViewController.js"; 
                    public const string VehicleDataViewController_js = "~/Scripts/ViewController/VehicleDataViewController.js"; 
                    public const string VehicleUploadViewController_js = "~/Scripts/ViewController/VehicleUploadViewController.js"; 
                    public const string VehicleViewController_js = "~/Scripts/ViewController/VehicleViewController.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string handlebars_latest_js = "~/Scripts/handlebars-latest.js"; 
                public const string handlebars_min_latest_js = "~/Scripts/handlebars.min-latest.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_ui_1_9_2_js = "~/Scripts/jquery-ui-1.9.2.js"; 
                public const string jquery_ui_1_9_2_min_js = "~/Scripts/jquery-ui-1.9.2.min.js"; 
                public const string jquery_ui_datepicker_es_js = "~/Scripts/jquery.ui.datepicker-es.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string jquery_validationEngine_es_js = "~/Scripts/jquery.validationEngine-es.js"; 
                public const string jquery_validationEngine_js = "~/Scripts/jquery.validationEngine.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class minified 
                    {
                        public static partial class images 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                            public const string jquery_ui_min_css = "~/Content/themes/base/minified/jquery-ui.min.css";
                            public const string jquery_ui_accordion_min_css = "~/Content/themes/base/minified/jquery.ui.accordion.min.css";
                            public const string jquery_ui_autocomplete_min_css = "~/Content/themes/base/minified/jquery.ui.autocomplete.min.css";
                            public const string jquery_ui_button_min_css = "~/Content/themes/base/minified/jquery.ui.button.min.css";
                            public const string jquery_ui_core_min_css = "~/Content/themes/base/minified/jquery.ui.core.min.css";
                            public const string jquery_ui_datepicker_min_css = "~/Content/themes/base/minified/jquery.ui.datepicker.min.css";
                            public const string jquery_ui_dialog_min_css = "~/Content/themes/base/minified/jquery.ui.dialog.min.css";
                            public const string jquery_ui_menu_min_css = "~/Content/themes/base/minified/jquery.ui.menu.min.css";
                            public const string jquery_ui_progressbar_min_css = "~/Content/themes/base/minified/jquery.ui.progressbar.min.css";
                            public const string jquery_ui_resizable_min_css = "~/Content/themes/base/minified/jquery.ui.resizable.min.css";
                            public const string jquery_ui_selectable_min_css = "~/Content/themes/base/minified/jquery.ui.selectable.min.css";
                            public const string jquery_ui_slider_min_css = "~/Content/themes/base/minified/jquery.ui.slider.min.css";
                            public const string jquery_ui_spinner_min_css = "~/Content/themes/base/minified/jquery.ui.spinner.min.css";
                            public const string jquery_ui_tabs_min_css = "~/Content/themes/base/minified/jquery.ui.tabs.min.css";
                            public const string jquery_ui_theme_min_css = "~/Content/themes/base/minified/jquery.ui.theme.min.css";
                            public const string jquery_ui_tooltip_min_css = "~/Content/themes/base/minified/jquery.ui.tooltip.min.css";
                        }
                    }
                    public static class Assets
                    {
                        public const string jquery_ui_css = "~/Content/themes/base/jquery-ui.css";
                        public const string jquery_ui_accordion_css = "~/Content/themes/base/jquery.ui.accordion.css";
                        public const string jquery_ui_all_css = "~/Content/themes/base/jquery.ui.all.css";
                        public const string jquery_ui_autocomplete_css = "~/Content/themes/base/jquery.ui.autocomplete.css";
                        public const string jquery_ui_base_css = "~/Content/themes/base/jquery.ui.base.css";
                        public const string jquery_ui_button_css = "~/Content/themes/base/jquery.ui.button.css";
                        public const string jquery_ui_core_css = "~/Content/themes/base/jquery.ui.core.css";
                        public const string jquery_ui_datepicker_css = "~/Content/themes/base/jquery.ui.datepicker.css";
                        public const string jquery_ui_dialog_css = "~/Content/themes/base/jquery.ui.dialog.css";
                        public const string jquery_ui_menu_css = "~/Content/themes/base/jquery.ui.menu.css";
                        public const string jquery_ui_progressbar_css = "~/Content/themes/base/jquery.ui.progressbar.css";
                        public const string jquery_ui_resizable_css = "~/Content/themes/base/jquery.ui.resizable.css";
                        public const string jquery_ui_selectable_css = "~/Content/themes/base/jquery.ui.selectable.css";
                        public const string jquery_ui_slider_css = "~/Content/themes/base/jquery.ui.slider.css";
                        public const string jquery_ui_spinner_css = "~/Content/themes/base/jquery.ui.spinner.css";
                        public const string jquery_ui_tabs_css = "~/Content/themes/base/jquery.ui.tabs.css";
                        public const string jquery_ui_theme_css = "~/Content/themes/base/jquery.ui.theme.css";
                        public const string jquery_ui_tooltip_css = "~/Content/themes/base/jquery.ui.tooltip.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Site_css = "~/Content/Site.css";
                public const string validationEngine_jquery_css = "~/Content/validationEngine.jquery.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


