CREATE TABLE [dbo].[SAIR_OPERARIOS]
(
[OPER_Id] [int] NOT NULL IDENTITY(1, 1),
[OPER_cApellidoPaterno] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[OPER_cApellidoMaterno] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[OPER_cNombre] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[OPER_cCorreo] [nvarchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[VEHI_Id] [int] NULL,
[PUES_Id] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SAIR_OPERARIOS] ADD CONSTRAINT [PK__SAIR_OPE__738AC7A6B290B23D] PRIMARY KEY CLUSTERED  ([OPER_Id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SAIR_OPERARIOS] ADD CONSTRAINT [FK__SAIR_OPER__VEHI___182C9B23] FOREIGN KEY ([VEHI_Id]) REFERENCES [dbo].[SAIR_VEHICLE] ([Codigo])
GO
