CREATE TABLE [dbo].[SAIR_OPERATIONS]
(
[OPER_Id] [int] NOT NULL IDENTITY(1, 1),
[OPER_Name] [nvarchar] (80) COLLATE Modern_Spanish_CI_AS NULL,
[OPER_DBName] [nvarchar] (80) COLLATE Modern_Spanish_CI_AS NULL,
[OPER_DBId] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SAIR_OPERATIONS] ADD CONSTRAINT [SAIR_OPER_PK] PRIMARY KEY CLUSTERED  ([OPER_Id]) ON [PRIMARY]
GO
